# Generated by Django 2.1.4 on 2018-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0003_auto_20181212_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='coords',
            field=models.CharField(max_length=40),
        ),
    ]
