# Generated by Django 2.1.4 on 2018-12-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
    ]
